// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sltpkmltwrtdrqfjkxno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsdHBrbWx0d3J0ZHJxZmpreG5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MzM5NDAsImV4cCI6MjA3NDEwOTk0MH0.1vg7CoVqx01YAUqOzVQX9WUJqQ9Ya0YtpaXujYWzyj4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});